import './globals.css'
import { Tajawal } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.rtl.min.css';

const tajawal = Tajawal({ 
  weight: ['200','300','400', '700','800','900'],
  subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ar" dir='rtl'>
      <body className={tajawal.className}>{children}</body>
    </html>
  )
}
